export { Hero } from "./Hero/Hero";
export { Cta } from "./CTA/Cta";
export { Search } from "./Search/Search";
export { Story } from "./Story/Story";
export { Call } from "./Call/Call";
export { Testimonials } from "./Testimonials/Testimonials";
export { Container } from "./Container/Container";
export { Newsletter } from "./Newsletter/Newsletter";
export { Footer } from "./Footer/Footer";
